version: "2.19.1"

services:
  app:
    build: 
      context: .
    ports: 
      - "8000:8000"

    volumes:
      - ./backend:/backend
    
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 

    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=12546
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12546
